name: Update README Snake
on:
  schedule:
    # 매일 KST 오후 6시 → UTC 09:00
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      # 1) 코드 체크아웃 + 브랜치 고정
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true  # GITHUB_TOKEN 을 이용해 같은 브랜치에 푸시

      # 3) 스네이크 SVG 생성
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: khp9798
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=#58A6FF

      # 4) 커밋 & 기본 브랜치에 푸시
      - name: Commit & Push
        run: |
          git add dist/*.svg
          git commit -m "chore: update GitHub Snake at $(date -u +"%Y-%m-%d %H:%M UTC")"
          git push origin master  # 또는 repo의 default branch 이름(main)
